### ISSUE TITLE
Enable view options in Windows

### ISSUE THREAD

**Issue by illithics** [BitHighlander/keepkey-desktop#183]
Unable to view or select developer tools in Windows Keep Key Desktop App

Recreate:
Install app on Win10
Load wallet
Unable to see toolbar options such as View

**Comment by illithics** [comment]
![Image](https://user-images.githubusercontent.com/47842709/198132343-6ebf82ff-be54-422a-ab38-df21aa4da537.png)

**Comment by amitojsingh366** [comment]
You need to press "Alt" for the toolbar to show, I had disabled it from showing by default since it doesn't look good on windows.
Should I change it back to the default behavior?

**Comment by illithics** [comment]
Thanks amitojsingh366, it looks better without being on by default and I was able to see it by pressing alt. Let's leave it.
