### ISSUE TITLE
(KICKBACK)(WALLET_CONECT)(API) combine wallet connect pairings with API pairings

### ISSUE THREAD

**Issue by BitHighlander** [BitHighlander/keepkey-desktop#239]
tasks:

* show all pairings on pairings page (Wallet connect + api)
* on click on pairing in pairing page launch page in browser tab
* validate the ability to restart

**Comment by amitojsingh366** [comment]
this is currently not possible since our wallet connect api only allows us to pair one app at a time

**Comment by BitHighlander** [comment]
We need a history of all the previous apps you have paired too. 

This is a security thing. We want users to know all the apps they have interacted with

Pairings should show all previously paired apps if wallet connect isnt current connected. 

(and perhaps save something that lets them start a wallet connect back up easy)
